language: go
go:
- 1.4
install: 
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cmd/cover 
  - go get github.com/mattn/goveralls
script: 
  - godep go test -v -cover -race -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci
